### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by licaon-kter** [accrescent/accrescent#139]
Since the client is already ["production ready"](https://github.com/accrescent/accrescent/issues/66#issuecomment-1201527423) how do you feel about inclusion in F-Droid?

**Comment by lberrymage** [comment]
Hi there! Given the security requirements of Accrescent and the fact that it can update itself, I'm not interested in publishing it on alternative stores.

**Comment by tiptoptom** [comment]
But for the first installation it would be nice to get it on f-droid. Also more people could notice it that way.

**Comment by rusty-snake** [comment]
> But for the first installation it would be nice to get it on f-droid.

1. You would still need to manually update it once from accrecent (and then never again from f-droid) for unattached updates to work.
2. For self updater to work at all it must be signed by the signing key of accescent not f-droid. 

Maybe it makes more sense to add the apk from GitHub Release to Izzys repo?

> Also more people could notice it that way.

**Comment by BHydden** [comment]
> Maybe it makes more sense to add the apk from GitHub Release to Izzys repo?

He's already addressed the option of putting it on any alternative store. 

> I'm not interested in publishing it on alternative stores.

**Comment by roke-julian-lockhart** [comment]
**https://github.com/accrescent/accrescent/issues/139#issuecomment-1868501539**

> For self updater to work at all it must be signed by the signing key of accescent not f-droid.

@rusty-snake, use reproducible builds then. Allows you to use your own signing key instead of F-Droid's.
