### ISSUE TITLE
Notification for when an app is automatically updated through Accrescent

### ISSUE THREAD

**Issue by matchboxbananasynergy** [accrescent/accrescent#157]
When an app is updated through Accrescent automatically, you should get a notification that says something along the lines of "`app_name` has been updated successfully." or something similar.

Unattended updates are a godsend, but it would be nice to actually know when something is updated, so I'm not perplexed when the app changes in some way when I'm unaware that it has updated in the first place.

**Comment by S7venLights** [comment]
And a changelog would be useful, perhaps a link to the Github/Lab/code page also. Developers/maintainers could include this when they submit an app to the store. 
That way if they don't have time to include the change log in accrescent, users could go check the Git…
