### ISSUE TITLE
Built-in DoH for even more secure connections

### ISSUE THREAD

**Issue by ghost** [accrescent/accrescent#189]
There is already TLS pinning but I think also having DNS over HTTPS inside the app would be great

**Comment by lberrymage** [comment]
I'm not immediately certain whether this fits into the scope of Accrescent, so I'll leave this issue open for discussion.

**Comment by ghost** [comment]
DNSSEC is only for validation (or am I wrong?), encrypted DNS would stop the data manipulation in the first place

> what about people who prefer ODoH? DoQ? DNSCrypt?

I still think some kind of option is better than none. Personally I would use any of those

Edit: sorry it seems like I broke GitHub

**Comment by ghost** [comment]
DNSSEC is only for validation (or am I wrong?), encrypted DNS would stop the data manipulation in the first place

> what about people who prefer ODoH? DoQ? DNSCrypt?

I still think some kind of option is better than none. Personally I would use any of those

**Comment by lberrymage** [comment]
What's the rationale for including this functionality in Accrescent though? Android already has native support for DoH, and supporting it directly in Accrescent brings new concerns to the table, e.g., certain DoH servers would be preferred which users might not expect, and forcing DoH when users are using a VPN would cause DNS leaks.

**Comment by ghost** [comment]
In my opinion, it depends on who you see as your target audience. More advanced users will surely use systemwide Private DNS option, but normal users may just not know about it. As an extreme workaround, the app could just connect to the IP of the server directly, like Telegram. Of course it would only work if the server's IP is totally static, or if the app could fallback to some kind of DNS

**Comment by lberrymage** [comment]
Because Android implements DoH and there are concerns with implementing DoH within Accrescent itself, I'm going to close this as out-of-scope.
