### ISSUE TITLE
Install of Accrescent fails because of package parsing

### ISSUE THREAD

**Issue by RemyBorius** [accrescent/accrescent#198]
Install of Accrescent fails with popus error "There was a problem parsing the package."

Phone is samsung s10e SM-G970F
OS is android 11, dotos 5.2

**Comment by matchboxbananasynergy** [comment]
Accrescent currently only supports Android 12 and up, which is why you can't install it. It may support earlier versions of Android eventually, however.

**Comment by RemyBorius** [comment]
Damn I miss the info sry

**Comment by lberrymage** [comment]
For future reference it's mentioned here: https://accrescent.app/#download

> Accrescent currently runs on Android 12 and up.

I'm considering adding Android 11 support in the near future though.

**Comment by BHydden** [comment]
I thought only 12 up supported unattended updates? 🤔

**Comment by lberrymage** [comment]
Correct. If Android 11 or below were supported, installations on those OSs wouldn't support unattended updates and would instead be forced to take the approach described in https://github.com/accrescent/accrescent/issues/155.
