### ISSUE TITLE
Accrescent shows wrong version

### ISSUE THREAD

**Issue by rusty-snake** [accrescent/accrescent#205]
Accrescent:

![Version: 0.11.1, Versionscode: 22](https://user-images.githubusercontent.com/41237666/227800842-7d741f4f-f5ee-4a39-8de2-f19ebe206f9c.png)

Settings:

![Version: 0.10.0, Versionscode: 22](https://user-images.githubusercontent.com/41237666/227800920-32aa6c9d-e996-49ff-896b-5ce4ac7a9987.png)

With GrapheneOS on Pixel 6.

Aves and Connecticut You are shown correct.  Exif Ereaser is shown with the Version of the not yet installed bit available update on the installed tap.

**Comment by BHydden** [comment]
Confirm I see the same on my P6

**Comment by lberrymage** [comment]
Resolved.
