### ISSUE TITLE
Add screenshots 

### ISSUE THREAD

**Issue by T8RIN** [accrescent/accrescent#214]
As a potential user i cannot see which app i'm downloading, please add screenshots to the readme👀

**Comment by matchboxbananasynergy** [comment]
Are you referring to screenshots of Accrescent itself, or screenshots of the apps uploaded to Accrescent?

If you mean adding screenshots to the apps on the store, that is being tracked here:

https://github.com/accrescent/meta/issues/16

**Comment by T8RIN** [comment]
I'm referring to screenshots of accrescent app
