### ISSUE TITLE
Open app listing from 'Update finished' notification

### ISSUE THREAD

**Issue by treequell** [accrescent/accrescent#237]
Enhancement idea. Tap the 'Update finished' notification to open the app listing in Accrescent.

If app listings in Accrescent include changelogs, this functionality could be particularly desirable.

**Comment by PatrykMis** [comment]
You're absolutely right. I hate those ''no changelog provided'' messages on G** Store, or repeated same messages for few years for popular big tech apps. So I'd love that feature.
