### ISSUE TITLE
App description 

### ISSUE THREAD

**Issue by w9925** [accrescent/accrescent#243]
Please add descriptions to that app. Also some infos about the dev/project and screenshots would be nice

**Comment by lberrymage** [comment]
App descriptions are being tracked at https://github.com/accrescent/meta/issues/14, and screenshots are being tracked at https://github.com/accrescent/meta/issues/16. I'll create a new issue for developer pages.

**Comment by lberrymage** [comment]
Developer/project pages are now being tracked at https://github.com/accrescent/meta/issues/21
