### ISSUE TITLE
Hide/disable "Open" button when app is disabled

### ISSUE THREAD

**Issue by lberrymage** [accrescent/accrescent#262]

**Comment by matchboxbananasynergy** [comment]
I think the best way to approach this might be for the open button to be greyed out, and when someone presses it, it should say "App is disabled."

**Comment by ghost** [comment]
Isn't it possible to add an "enable" button in place of "open" button?

**Comment by matchboxbananasynergy** [comment]
It should be. The "enable" button could take one to the app info screen through which they can re-enable it.

**Comment by ghost** [comment]
> It should be. The "enable" button could take one to the app info screen through which they can re-enable it.

I have seen Play Store doing this without taking to any other screen on other android devices.
Maybe it's due to it's privileged state.
But yes that would be good too.
But I guess a button to view app info screen must be persistant always.

**Comment by ghost** [comment]
> > It should be. The "enable" button could take one to the app info screen through which they can re-enable it.
> 
> I have seen Play Store doing this without taking to any other screen on other android devices.
> Maybe it's due to it's privileged state.
> But yes that would be good too.
> But I guess a button to view app info screen must be persistant always.
>

Created a github issue for the enhancement

https://github.com/accrescent/accrescent/issues/269
