### ISSUE TITLE
Pitch black background setting

### ISSUE THREAD

**Issue by soupslurpr** [accrescent/accrescent#279]
Would be cool to have an option to enable a pitch black background while still keeping the rest of the theme

**Comment by lberrymage** [comment]
I'm not sure I want to have this implemented. Generally the Material spec is good at maintaining appealing color contrast, and having a full black background doesn't really do that. There are advantages to Accrescent having a consistent look as well.

Curious what others have to say.

**Comment by soupslurpr** [comment]
Fair, but I did see that when the pitch black background is on, it seems the other colors adjust to it 

Edit: actually only the bottom bar color gets adjusted

**Comment by PatrykMis** [comment]
Personally I more like Accrescent when black variant of dark theme in LineageOS is turned on, which is impossible on e.g. GrapheneOS. If pitched black works similarly as with black theme turned on LineageOS I'd prefer to have this option.

**Comment by BHydden** [comment]
I also prefer black theme

**Comment by idk-r-n** [comment]
> I'm not sure I want to have this implemented. Generally the Material spec is good at maintaining appealing color contrast, and having a full black background doesn't really do that. There are advantages to Accrescent having a consistent look as well.
> 
> Curious what others have to say.

Don't cave to the pressure. You are correct. 🌙🌙🌙

**Comment by ghost** [comment]
> I'm not sure I want to have this implemented. Generally the Material spec is good at maintaining appealing color contrast, and having a full black background doesn't really do that. There are advantages to Accrescent having a consistent look as well.
> 
> Curious what others have to say.

You are right.
I vote for not implementing this.
Even if you implement it, make it as a toggle and turn the toggle off by default.
Pls don't do the way Molly does.

**Comment by PatrykMis** [comment]
Absolutely agree with turning it off by default if you finally implement it.

**Comment by soupslurpr** [comment]
> Absolutely agree with turning it off by default if you finally implement it.

Yeah, its off by default in my pull request https://github.com/accrescent/accrescent/pull/280

**Comment by lberrymage** [comment]
I'm going to decline this feature for now under the premise that it may become more effort to maintain over time to ensure the deep black doesn't inadvertently conflict/merge with other UI elements. Part of the rationale for using Material 3 consistently is avoiding accumulating UI color quirks as more elements are added.

If there's significant interest in the future I may reconsider, but I can't really justify it now.

**Comment by Ganwtrs** [comment]
I like pitch black themes because I'm pretty sure they're a bit better than normal dark themes for battery, and the RGB being 000000 means there's no blue light for the background
