### ISSUE TITLE
Restore Settings accessibility

### ISSUE THREAD

**Issue by PatrykMis** [accrescent/accrescent#291]
Unfortunately, From v0.13.0 (especially from PR #286), there is unlabeled "back" button. Further more, using screen readers like TalkBack it is now impossible to get know that the settings entry is a switch and what is current state of the switch. It definitely breaks 4.1.2 criterion (level A) of the Web Content Accessibility Guidelines.

We all know Accrescent's GUI is made with Compose, so we, and all developers should aware at least of this links:

* [Accessibility in Compose ](https://developer.android.com/jetpack/compose/accessibility)
* [Accessibility in Jetpack Compose](https://developer.android.com/codelabs/jetpack-compose-accessibility#0)

**Comment by PatrykMis** [comment]
I'll look into it and try to improve as much as I can in next few days.

**Comment by PatrykMis** [comment]
checklist:

* [ ] Remove "App icon" from `contentDescription` because its repetition when navigating across apps list isn't nessesary.
* [ ] Make back button (if present) and top bar the first elements on the screen when navigating via TalkBack. It is rule of thumb for all AOSP and 3rd party accessible apps.
* [ ] Make settings entries properly marked as switches and announce their states.

**Comment by lberrymage** [comment]
Thank you for making me aware of this so quickly and linking to the documentation! I'll admit, this wasn't on my mind when reviewing that PR. I'll review those links and try to make myself more conscientious of accessibility implications for future changes.

Once that PR is approved I'll cut a bugfix release to address these issues.

**Comment by PatrykMis** [comment]
In my PR, the only thing I can't do is focus order , but, in fact, it is not related to v0.13.0 but v0.11.0 or something like that.

in regular apps, focus order is the following: top bar (eventual back button, app name, more controls like settings, search etc.), main content, bottom sheet (here would be Apps/Installed/Updates).

In Accrescent currently it is: main content, top bar, bottom sheet.

Unfortunately, it's out of my knowledge to fix it properly. What I have noticed: proper order in the code usually means proper focus order. You can see it e.g. [here](https://github.com/google-developer-training/basic-android-kotlin-compose-training-cupcake).

**Comment by lberrymage** [comment]
That could very well have something to do with the somewhat hacky way the top app bar is handled currently.

https://github.com/accrescent/accrescent/blob/d654d5594aa7668f714a7789d03bea85e5c19452/app/src/main/java/app/accrescent/client/ui/MainActivity.kt#L147-L192

I wouldn't be surprised if a proper refactor of that code fixed the focus order.
