### ISSUE TITLE
Possibility to add repositories?

### ISSUE THREAD

**Issue by gallegonovato** [accrescent/accrescent#297]
Good evening:

I know you are looking for a different store for applications. And to stand out from the rest. And maybe I'm screwing up by making this suggestion.

I don't know if in the future you could add repositories or possible sources of new apps. So as to have more applications inside accrescent.

I apologize if I did something wrong with my question. It was not my intention. 

Best regards

**Comment by PatrykMis** [comment]
<https://accrescent.app/faq#other-repos>

**Comment by lberrymage** [comment]
As mentioned above, Accrescent won't support third-party repositories. A couple reasons not yet mentioned on the site are technical complications with having the same app in multiple repositories and inconsistent quality control measures. Thank you for the question though.
