### ISSUE TITLE
Article about the project

### ISSUE THREAD

**Issue by infoekcz** [accrescent/accrescent#303]
Hello,
I really like your project and I see a great future for it. I wrote an article about it in Czech: https://infoek.cz/accrescent-je-svobodny-obchod-s-aplikacemi-jak-ho-nainstalovat-2023/
I would like to inform more developers that Accrescent exists, so that there is more content in it. ;)

Thanks!

**Comment by lberrymage** [comment]
Thank you! I really appreciate the support and the work!

**Comment by infoekcz** [comment]
I looked at the Czech translation. Hopefully soon the app will be in my language too. :)
https://hosted.weblate.org/user/infoekcz/
