### ISSUE TITLE
Refresh the app list on app start

### ISSUE THREAD

**Issue by lamarios** [accrescent/accrescent#365]
The app almost works on TV. The only issue is that there is no swipe down to refresh on TV, I tried on an emulator so i can swipe down to refresh and once the app list is there it is usable to download and update apps without an other changes. 

Given that there are a couple of apps that have a TV UI, that will be very helpful for users of those.

**Comment by lberrymage** [comment]
When did you last try this? Accrescent should refresh on app start since https://github.com/accrescent/accrescent/commit/12e252c4d1c806d557ebddd02eb8a4913ac01c07.

**Comment by lamarios** [comment]
Today in an emulator. I downloaded the release from the website and installed it with adb.

**Comment by lamarios** [comment]
ok, it was v1.15.1 and it was not working.
I tried with 1.15.2 and it is working now.

**Comment by lberrymage** [comment]
Great!
