### ISSUE TITLE
Enable MTE

### ISSUE THREAD

**Issue by lberrymage** [accrescent/accrescent#368]
https://developer.android.com/ndk/guides/arm-mte#production

There needs to be a known way to test this in an emulator before it is implemented since we don't have a test device with MTE support.

**Comment by BHydden** [comment]
Someone tested it for @soupslurpr when he added it to BeauTyXT but I forget who. Maybe he can get it tested for Accrescent also.

**Comment by lberrymage** [comment]
I would need a way to test it myself since it would need testing more than once, e.g., when a dependency with native code is updated (we don't currently have any such dependency, but we need to have a plan for when we do).

**Comment by PatrykMis** [comment]
I can test too if needed.

**Comment by soupslurpr** [comment]
Can't you test with HWAddress Sanitizer? But that does not detect stack allocation memory safety I think. Well I don't see it mentioned in https://developer.android.com/ndk/guides/hwasan and for MTE detecting stack allocation memory safety needs you to compile the code with the -fsanitize=memtag compiler flag.

**Comment by PatrykMis** [comment]
Tested every functionality with MTE enabled and everything works.

**Comment by lberrymage** [comment]
> Can't you test with HWAddress Sanitizer? But that does not detect stack allocation memory safety I think. Well I don't see it mentioned in https://developer.android.com/ndk/guides/hwasan and for MTE detecting stack allocation memory safety needs you to compile the code with the -fsanitize=memtag compiler flag.

The point of testing MTE is to ensure that something critical (specifically automatic updates) isn't broken by enabling it, so using other tools to detect memory safety issues doesn't fully accomplish that. However, since we aren't currently using any native code, I've changed my mind on this and am enabling MTE now. We'll just have to rigorously test critical code paths such as the update system when we eventually do add native code.
