### ISSUE TITLE
Package name at the bottom view is cut

### ISSUE THREAD

**Issue by meenbeese** [accrescent/accrescent#380]
I'm currently facing an issue with the latest version of Accrescent (0.15.3) on my Galaxy S20+. Normally, the package name should be visible at the bottom of the app page. However, I can only see a small part of it, with the majority being cut off. I've taken a screenshot to illustrate this problem: <br/>
<img src="https://github.com/accrescent/accrescent/assets/114044633/ae623e1a-5649-4c77-9d76-dac626d74d00" width="540" height="1164">

**Comment by soupslurpr** [comment]
Its not visible at all for me, Pixel 7

**Comment by taivlam** [comment]
[Application ID](https://developer.android.com/build/configure-app-module#set-application-id) is being blocked on the bottom of the screen for the following devices running the latest version of GrapheneOS:

* Pixel 4a (`sunfish`, Android 13 `2024010700`),
* Pixel 5a (`barbet`, Android 14 `2024011600`), and
* Pixel Tablet (`tangorpro`, Android 14 `2024011600`)

All devices are have Accrescent version `0.16.1`.

Below are screenshots of how this looks like.  (Results may depend on specific options chosen for display size, i.e. chosen in this UI path: Settings app > Display >  Display size and text.)

## Screenshots
### Pixel 4a
App ID is blocked in portrait, but visible in landscape.

<img src="https://github.com/accrescent/accrescent/assets/47955724/cdebab32-51b8-414c-846a-45fe3792980e" alt="Pixel 4a in portrait" height="600"><br>

<img src="https://github.com/accrescent/accrescent/assets/47955724/27d36dea-b0fd-4d08-9ec0-30c314cac3b0" alt="Pixel 4a in landscape" height="200"><br>

### Pixel 5a
Similarly, app ID is blocked in portrait, but visible in landscape.

<img src="https://github.com/accrescent/accrescent/assets/47955724/b86efb60-fcdc-4e87-973a-7388934562a8" alt="Pixel 5a in portrait" height="600"><br>

<img src="https://github.com/accrescent/accrescent/assets/47955724/ee9c9c67-0af3-4257-b430-281afa0fe93e" alt="Pixel 5a in landscape" height="200">

### Pixel Tablet
App ID is completely block in both portrait and landscape.

<img src="https://github.com/accrescent/accrescent/assets/47955724/ba6677da-6cd6-4275-8251-096ccf247df0" alt="Pixel Tablet in portrait" height="600"><br>

<img src="https://github.com/accrescent/accrescent/assets/47955724/dcb830c1-7155-4214-be90-62afb5680f13" alt="Pixel Tablet in landscape" height="200"><br>
