### ISSUE TITLE
accrescent inclusion policy

### ISSUE THREAD

**Issue by Pantyhose-X** [accrescent/accrescent#394]
## What are the requirements an app must meet to be included with the repo?
The app …

* Trademarks must not be infringed
*  Remove the in-app updater
 * Remove Dangerous Permissions
 * Remove Google’s proprietary “Play Services” either using microG or removing Non-Free dependencies completely
* it must not download additional executable binary files (e.g. addons, auto-updates, etc.) without explicit user consent. Consent means it needs to be opt-in (it must not be harder to decline than to accept or presented in a way users are likely to press accept without reading) 

* **Tracking & advertising** Cookies no ip & GPS coordinates latitude
Third-party analysis libraries in the form of proprietary software are not accepted
 
 
 * directory/file structure
[fastlane](https://github.com/fastlane/fastlane) | [GPP](https://github.com/Triple-T/gradle-play-publisher) | [Gradle](https://gradle.org/) | [tauri](https://github.com/tauri-apps/tauri)

**Comment by lberrymage** [comment]
Hi! All Accrescent publishing requirements are documented at https://accrescent.app/docs/guide/appendix/requirements.html. If you have any specific suggestions, please feel free to mention them as such, but to prevent people from getting confused I'm going to close this issue.
