### ISSUE TITLE
Option to set Theme

### ISSUE THREAD

**Issue by inson1** [accrescent/accrescent#433]

**Comment by lberrymage** [comment]
By default, Accrescent uses the system theme, and both light and dark themes are supported. All that needs to be done here is adding a choice in the settings to choose between system, dark, or light theme.

**Comment by BHydden** [comment]
And maybe a black theme too if dark isn't black.

**Comment by PatrykMis** [comment]
And also remembering that if Dynamic You Theming is enabled, the option to manually choose theme should be unavailable for clarity.

**Comment by inson1** [comment]
I think in that case that element should be disabled, maybe with some note about it in description?
