### ISSUE TITLE
Erro ao atualizar 

### ISSUE THREAD

**Issue by aaklippel** [accrescent/accrescent#439]
Uma nova versão do Accrescent está disponível para atualizar, porém não atualiza...

**Comment by lberrymage** [comment]
What version of Accrescent do you have installed? Has it updated since you posted this issue?

**Comment by aaklippel** [comment]
A versão que aconteceu o erro foi a 0.17.0, aí saiu uma atualização, porém
não atualizava, não baixava e não mostrava nada, aí desinstalei e fiz o
download direto.

Em sex., 1 de mar. de 2024, 4:08 AM, Logan Magee ***@***.***>
escreveu:

**Comment by lberrymage** [comment]
Closing as not reproducible. See also https://github.com/accrescent/accrescent/issues/531.
