### ISSUE TITLE
I discovered Accrescent accepts also closed source app

### ISSUE THREAD

**Issue by serrq** [accrescent/accrescent#479]
I no more support this app. 
Sorry, I don't want closed source apps because I want controlling the code of all installed apps on my devices. Always.

**Comment by PatrykMis** [comment]
Open source doesn't necessarily mean more secure. I'm aware of many open source apps with numerous well-known security vulnerabilities, as well as many closed-source apps that are highly secure. Furthermore, Accrescent will have a filter to, for example, show only open source apps, so your treatment is incomprehensible.

**Comment by matchboxbananasynergy** [comment]
People are welcome to use Accrescent or not according to their needs.

That said, as Patryk above said, Accrescent will offer an `open-source` tag for open-source apps, so that if one only wants open-source apps, they can filter for that.

**Comment by serrq** [comment]
Sorry but I don't follow your need to support closed source apps.
Your vision is not necessarily my vision (and of course vice versa).

All the best.

**Comment by rusty-snake** [comment]
> because I want controlling the code of all installed apps on my devices.

In https://github.com/accrescent/accrescent/issues/473#issuecomment-2039150102 you said 

> I cannot verifying a package signature because I am not a developer.

So what do *you* want with the code?

**Comment by serrq** [comment]
> So what do you want with the code?

The fact that I am not a developer does not prevent me from delegating a professional to do a check on a certain code.

The problem is not who should do a code check, but whether it is possible to do a code check (where circumstances so require).

**Comment by PatrykMis** [comment]
How many times you've hired a professional to check the code? It's obviously rhetorical question.

**Comment by serrq** [comment]
Stop stop stop. I don't want starting a toxic discussion.

I already answer to your curiosity and request of more details.

I have nothing against your vision about closed source apps.

In my devices I took decision to exclude close source apps.
Specifically I don't want mix closed source apps with open sources ones.
It isn't a question of word filter, but I don't want fishing in a lake with barracudas, even if I have a protection.

Good evening.

**Comment by lberrymage** [comment]
I'm going to lock this thread since I don't it's productive to continue this conversation here. People may prefer to use only open-source software, and if so, Accrescent may not meet their needs, and that's fine. Discussion on the merits of using only open-source software isn't on-topic for this repository.
