### ISSUE TITLE
Add GitHub Action updating MIN_TIMESTAMP every X weeks

### ISSUE THREAD

**Issue by lberrymage** [accrescent/accrescent#51]
As a follow up to #50 and https://github.com/accrescent/accrescent/commit/13a4d6dc3a131111941fc366e29c158be1c5eec8, make a GitHub Action that makes a PR to update MIN_TIMESTAMP to the latest published value every X weeks. The frequency isn't important to begin with but once every month seems reasonable given where Accrescent is in development currently.

**Comment by ghost** [comment]
zamn
