### ISSUE TITLE
Updating Accrescent resets the app language from Norwegian Nynorsk to the Android system language

### ISSUE THREAD

**Issue by ghost** [accrescent/accrescent#533]
(It's not a major issue as you can still reinstall Accrescent to get the app to display in Norwegian Nynorsk again).

_Background_
In Android, Norwegian Nynorsk is not counted as a "system language" (in other words, AOSP is not translated into said language), but can be set as the system's "preferred language". The intention of this is to tell apps that the user prefers Norwegian Nynorsk.

_Bug description_
When the language "Norsk nynorsk" (Norwegian Nynorsk) is set as the preferred language in Android's settings, updating Accrescent to a newer version results in the app resetting the app language back to the Android "system language".

See the first screenshot for an example of the Android language settings. 

I suspect that this occurs with all languages that do not have AOSP translations, but are set as "preferred" in the Android system language settings. But Accrescent is not translated into any other language that meets this criteria, so I can't check if this occurs for other languages that meet this criteria.

_Steps to reproduce_
1. Go to the Android Settings app > System > Languages > System Languages 
2. Select "Add languages", search for "nynorsk" and add it
3. Set it as the preferred language, and English as the second preferred language
4. Install an older version of Accrescent, such as 0.20
Observe that the app is displayed in Norwegian Nynorsk.
5. Update Accrescent to the newest version 
6. Open Accrescent again and observe that the language is displayed in English

Device: Pixel 8 
OS: GrapheneOS 2024062700

This is probably fixed by adding support for Android's "app language" feature: https://github.com/accrescent/accrescent/issues/288

![example1.png](https://github.com/accrescent/accrescent/assets/99329251/054f0227-6b3b-4aa1-bc1c-d40d92d869ea)

0.20:
![Screenshot_20240702-1035example1_v0.20.png](https://github.com/accrescent/accrescent/assets/99329251/c1ba966f-ddcd-49e9-98a9-6d47e4665d68)

Updated to 0.21:
![Screenshot_20240702-103eexample1_v0.21_upgrade.png](https://github.com/accrescent/accrescent/assets/99329251/5c9f5596-6e4d-4ee7-a3db-a0995a46039f)

**Comment by lberrymage** [comment]
This is definitely a bug. I'll try to produce a log and see why it's not installing the proper translation.

**Comment by lberrymage** [comment]
`Resources.getSystem().configuration.locales[0].language` is returning `en` under the configuration you described, which is why Accrescent attempts to install the English language split APK instead of the Nynorsk one. I'll need to find another way to retrieve the device locale which includes non-system languages (assuming the issue is indeed that the above API only returns system languages).
