### ISSUE TITLE
Richer app metadata

### ISSUE THREAD

**Issue by easrng** [accrescent/accrescent#546]
I'd like to see screenshots, a more detailed description, and links to the project/developer's website before I install an app.

**Comment by rusty-snake** [comment]
- https://github.com/accrescent/meta/issues/16
- https://github.com/accrescent/meta/issues/14
- https://github.com/accrescent/meta/issues/21

**Comment by lberrymage** [comment]
Closing as duplicate of existing issues per the above comment
