### ISSUE TITLE
Self Host Repositories & Manage 3rd Party Repositories In-App

### ISSUE THREAD

**Issue by trymeouteh** [accrescent/accrescent#554]
To be able to self host a 3rd party repository of apps and allow the client to have settings to add and remove 3rd party repositories. Many app stores do this such as F-Droid, Flatpaks, Scoop.

**Comment by lberrymage** [comment]
This is an intentional design choice made to avoid various practical and security-related issues. [The website](https://accrescent.app/faq#other-repos) briefly addresses some of them. I can explain in more detail if you like, but we don't plan to implement this.
