### ISSUE TITLE
Proposal: Translation of UI

### ISSUE THREAD

**Issue by Ilithy** [accrescent/accrescent#57]
Hi; Can we offer you translations of the user interface?
_(In my case, in French)_

I am aware that Accrescent is still at an early stage, and that many additions will be necessary before the first public publication, this is only a base that I will keep updated as additions are made (if it fits)

_I can do this via pull request, or by simply providing you the strings.xml file._

Thanks.

**Comment by lberrymage** [comment]
Hi and thanks for the offer! Yes, I'm willing to accept translations provided at least one other person reviews them. Like you pointed out, Accrescent is still in development, so I'm going to take a best-effort approach to translation maintenance for now.

Go ahead and make a PR.

Linking https://github.com/accrescent/meta/issues/5 for tracking purposes.

@Wonderfall would you be interested in reviewing this?

**Comment by Wonderfall** [comment]
Yeah, no problem.

**Comment by Ilithy** [comment]
@lberrymage: It's a great idea, I completely understand your point of view.

@Wonderfall: the simplest, I'll give you access to my fork, you can check and modify the files at your leisure :-)
