### ISSUE TITLE
Should we as a community ask app developers to start supporting Accrescent?

### ISSUE THREAD

**Issue by ghost** [accrescent/accrescent#607]
or should we wait until Accrescent reaches a more stable state?

**Comment by BHydden** [comment]
No not yet, please be patient. The app is not a polished experience on the dev end and Logan doesn't want to put people off. The app is in allow list only mode for new devs deliberately.

When Logan is ready to open it up and allow any dev to join, he'll let us know.

**Comment by ghost** [comment]
> No not yet, please be patient. The app is not a polished experience on the dev end and Logan doesn't want to put people off. The app is in allow list only mode for new devs deliberately.
> 
> When Logan is ready to open it up and allow any dev to join, he'll let us know.

I think it would be a good idea to write a note about this on the readme or the website so that the community can be made aware of this on a large scale.

**Comment by boredsquirrel** [comment]
I wonder how the devs are selected. It seems like a random list of random people?

Currently Accrescent hosts quite a few apps, and especially the essential ones (like MullvadVPN, Wireguard, Florisboard, Gallery, Aegis, KeepassDX, Image Toolbox, Orbot, NeoStumbler, Obtainium, StreetComplete, Syncthing-Fork, Localsend, Thunderbird Android) should be easy to get on there.

They have active devs, and when asking them I am sure a lot of people will have the patience to live with some inconveniences.

This would drastically improve the usability of Accrescent, catapult it to a "minimal set of essential apps" state.

**Comment by rusty-snake** [comment]
Essential ... for you

The thing is, that I do not want more organic maps that you need to ping after ever release.
https://github.com/organicmaps/organicmaps/issues/9663
https://github.com/orgs/organicmaps/discussions/9250#discussioncomment-10701999

**Comment by lberrymage** [comment]
@boredsquirrel They aren't randomly selected. I asked very few projects in the beginning whether they would be interested in publishing to Accrescent because I believed they would be valuable, but all of the others have contacted Accrescent directly to ask to be allowlisted for publication.
