### ISSUE TITLE
Open Source Status?

### ISSUE THREAD

**Issue by ghost** [accrescent/accrescent#622]
Hey I love the Store and I would love to see when I click on a App that it says Open Source or Closed Source. And that it shows if the App has Trackers and Logger.

And may I ask why closed Source Apps will be available in the Store? I can understand that something like 1Password is secure but in the End it is not the best in terms of Security, when the Code is not known...

**Comment by rusty-snake** [comment]
https://accrescent.app/faq#open-source

**Comment by ghost** [comment]
Thank you. Does this filtered which is mentioned there, will have checking on Trackers and Logger too?

**Comment by rusty-snake** [comment]
It can be very subjective what counts as Tracker and what not. Also having "Trackers" does not mean they are used (in GDPR violating ways). And detecting trackers does not work, you would have to rely on developers stating trackers=yes/no. So my guess is No.
I'm not involved in accrescent so this is not a No from the project.

Loggers will be included in every app.

**Comment by ghost** [comment]
But for example Exodus Privacy or Warden from AuroraOSS can detect Trackers. Okay. I don't think so, because when I look with Warden, then only a few show Logger, the most not.

**Comment by lberrymage** [comment]
Closing as duplicate of https://github.com/accrescent/meta/issues/25.

We don't have any plans to attempt to detect "trackers," since as @rusty-snake said, that label is very subjective and is not representative of an app's privacy practices.

**Comment by ghost** [comment]
Okay I understand thank you
