### ISSUE TITLE
[kind of OT] AppVerifier can not verify some apps installed via Accrescent

### ISSUE THREAD

**Issue by damko** [accrescent/accrescent#625]
just a heads up from a first time user

I've installed Appverifier, Molly, Beautytxt, Arcticons and Ivpn from Accrescent.

Appverifier verifies Molly and Beautytxt but can't verify arcticons and ivpn.

I understand that this an Appverifier "issue" that can [be solved in this way](https://discuss.grapheneos.org/d/14701-how-to-verify-apps-with-appverifier-that-are-not-in-the-internal-database/2) but I think that this highly confusing for a first time user who certainly expects to see a green check next to **any** application installed via Accrescent.

thank you for your work, very appreciated

**Comment by lberrymage** [comment]
Hi! AppVerifier isn't an Accrescent project and is maintained by @soupslurpr at https://github.com/soupslurpr/AppVerifier, so I think this issue would better be posted there.

**Comment by damko** [comment]
hello! thank you for your reply.

I think I wasn't able to make my point here so I'll try rephrase.

I'm aware that Appverifier is not part of your project but you have a handful of applications and Appverifier stands out in the list. I think that a new user will think that all the applications you have in your own repo certainly are registered in Appverifier internal database.
So, maybe in order to avoid confusion you could just contribute your listed applications' signature back to Appverifier so that new users won't feel disoriented?

my 2 cents

**Comment by soupslurpr** [comment]
@damko I'm not accepting contributions of new apps to AppVerifier's internal database

**Comment by damko** [comment]
well this solves the issue completely :-)
