### ISSUE TITLE
Notification for new Apps

### ISSUE THREAD

**Issue by ghost** [accrescent/accrescent#636]
Hey,

i think the App misses one nice and important Feature and that is to get a Notification when the Store gets new Apps. I would enjoy it a lot more, by receiving a Notification for that.

**Comment by lberrymage** [comment]
I don't think this is a helpful feature in the long term. When developer signups are open to the public, apps will presumably be published at a faster rate, and it could be bothersome to people to receive notifications about new applications they don't care about.

**Comment by ghost** [comment]
> I don't think this is a helpful feature in the long term. When developer signups are open to the public, apps will presumably be published at a faster rate, and it could be bothersome to people to receive notifications about new applications they don't care about.

Oh, when will it open up? But the ones who get bothered, could just turn it off? Or at least give us the Option to enable it in the Settings for the once, that would love to get them. I really don't understand what would be not helpful in them? I think for Users it is the other way around. Because sometimes I'm asking myself if this App is new or if I did just forgot it. I think having the Option in the Settings is a good thing in general.

**Comment by rusty-snake** [comment]
> Notification for new Apps

Please don't.

A simple RSS feed or a "Recently added Apps" and "Recently updated Apps" in the app (like in NeoStore) would be nice though.

**Comment by lberrymage** [comment]
> Oh, when will it open up?

There's no ETA for opening it up. There's a rough roadmap at https://github.com/orgs/accrescent/projects/4/views/2 though.

> But the ones who get bothered, could just turn it off?

I predict that most people would be bothered if it were on by default.

> I think having the Option in the Settings is a good thing in general.

Normally I'd be in favor of leaving an issue like this open and letting someone else contribute the code if they care about it, but this feature would have a limited lifetime by design, and I'm not in favor of adding features which have no future in the long-term vision of the project.

**Comment by ghost** [comment]
> > Notification for new Apps
> 
> Please don't.
> 
> A simple RSS feed or a "Recently added Apps" and "Recently updated Apps" in the app (like in NeoStore) would be nice though.

I agree with that! For me the Argument was not really about Notification. It was more about to know, which Apps are new. And this would be a lot better, than Notifications :-)

**Comment by ghost** [comment]
> > Oh, when will it open up?
> 
> There's no ETA for opening it up. There's a rough roadmap at https://github.com/orgs/accrescent/projects/4/views/2 though.

Okay, I understand.

> > But the ones who get bothered, could just turn it off?
> 
> I predict that most people would be bothered if it were on by default.

This could be right. Then off per default but whoever want, can enable it. But I would say that @rusty-snake mentioned a better Option, which would be to see new Apps, in an area in the App like "recently added or updated".

> > I think having the Option in the Settings is a good thing in general.
> 
> Normally I'd be in favor of leaving an issue like this open and letting someone else contribute the code if they care about it, but this feature would have a limited lifetime by design, and I'm not in favor of adding features which have no future in the long-term vision of the project.

I understand your point.
