### ISSUE TITLE
Discussion Area

### ISSUE THREAD

**Issue by ghost** [accrescent/accrescent#639]
Hey,

could you add a Discussion Area here in your Github Page? Because I know from many Apps, that they have the Discussion Area, to request Ideas, ask Questions or for general and more.

**Comment by lberrymage** [comment]
The chat community is currently on Matrix (though we may move  elsewhere in the future). The link can be found at https://accrescent.app/#social. I'd rather not open up GitHub Discussions now since it would fragment the community and add moderation burden.

**Comment by ghost** [comment]
> The chat community is currently on Matrix (though we may move elsewhere in the future). The link can be found at https://accrescent.app/#social. I'd rather not open up GitHub Discussions now since it would fragment the community and add moderation burden.

Oh, where will you move then? And I understand your point about Discussion, of course.

**Comment by lberrymage** [comment]
Most likely Discord, if anywhere.

**Comment by ghost** [comment]
Okay :-)
