### ISSUE TITLE
When ready?

### ISSUE THREAD

**Issue by Grkrz** [accrescent/accrescent#66]
Hi 
This is not a request and I am writing in the wrong place I know. 
But when the app will be ready to use?
Thank you!

**Comment by lberrymage** [comment]
Hi! I'm not sure exactly when it will be production-ready, but the roadmap can give you an idea of where we are right now: https://github.com/orgs/accrescent/projects/2.

The client is basically already production-ready and can be made backwards-compatible with future changes quite easily for the most part. The main work that needs to be done is fully implementing the app submission process in the [developer portal](https://github.com/accrescent/devportal).  Some groundwork is already laid but it needs to be secure and robust before entering public alpha (at which point developers will be able to upload apps to the store).

**Comment by Grkrz** [comment]
Thank you for long description! I want to thank you for the great job you are doing and wish you fast success with all the process of creation.🙂

**Comment by lberrymage** [comment]
Thanks! I appreciate the kind words.

**Comment by PatrykMis** [comment]
Appreciate this great work too! I could help with maintenance as I am not a programmer but I see this project has the best maintainers already. Anyway, I'm following this project on Github, Matrix and Twitter, and if I could do something - i will do that.
Hope this app will replace insecure and poorely-maintained F-Droid someday.

**Comment by lberrymage** [comment]
Thank you! Apart from programming, translations are welcome. We just put up experimental [Weblate](https://hosted.weblate.org/engage/accrescent/) support of you want to try contributing there, otherwise a PR is fine.

You can also help with documentation on [the website](https://github.com/accrescent/accrescent.app) but there's not much there at the moment. Documentation will become more important once there are instructions for how to use the upcoming developer portal.

And of course feature suggestions for any part of Accrescent are always appreciated 🤗.

**Comment by Grkrz** [comment]
Hello!
When it comes to idea generation I have got an idea how to reach to at least some of the apps developers.
I have written an email which I have allready sent to one developer. This hopefully will make them aware (of there already not) of this project. We need to make this running as fast as possible because is of a great importance.
Any suggestions to the form of this email are welcome.

"Hello Tutanota team!
I am writing to you to inform you about the new project: Accrescent. The project is fosued on private and secure way of distributing the apps to it's clients. 
I am trying to help developers to get in contact with app creators to make them aware of this project.
I want to ask you at least to take a look at this project https://accrescent.app/
For now it is in very early stage (pre-aplha) mainly for developers.
Hopefully I will see tutanota app in Accrescent sooner then later!🙂. 
Chears!


https://accrescent.app/
"

**Comment by lberrymage** [comment]
Hi! I appreciate the enthusiasm. We should probably hold off on reaching out to many app creators until Accrescent can actually accept apps. Currently there's no way to submit them (although that's being worked on).

Once Accrescent accepts app submissions then I'll say go ham on letting your favorite app developers know if you want.

**Comment by Grkrz** [comment]
Sure!
So for now I will work on PL translation and wait for the green light🙂.
