### ISSUE TITLE
Implement ETag checks to avoid unnecessary repodata fetches

### ISSUE THREAD

**Issue by lberrymage** [accrescent/accrescent#8]

**Comment by ghost** [comment]
@lberrymage
Could accrescent consider designing this and other features such that the client verifies it in a way that it cannot be used to track the user?
ETags can be used to fingerprint users, see http://www.arctic.org/%7Edean/tracking-without-cookies.html.

Perhaps this would require more research?

**Comment by lberrymage** [comment]
Thinking about it briefly, I don't see how this can be mitigated entirely without removing the use of ETags entirely. It could perhaps be partially mitigated by having the client choose a deterministic algorithm for generating the ETag (such as a predetermined hash function) and only accept/save a new ETag if it can be reproduced locally. However, this would require control over the server's ETag generation method, which would limit the environments we can deploy to and increase our infrastructure maintenance burden. But I haven't thought about this much, so there could be flaws in my logic here.

Unfortunately when it comes to other features, there are many practical ways to track users across network requests. This is largely due to app update checks and app installations themselves, since they reveal to the server which apps the client has installed from Accrescent as well as various device attributes used to obtain the correct split APKs such as the user's preferred language, device architecture, and screen pixel density. Once app listing localization is supported, this will provide another data point by which a specific client (or at least a smaller pool of clients) could be identified. The tracking potential of update checks could be mitigated by spreading out individual update checks for different apps over a significant period of time, but the problem of revealing identifying device attributes to the server is practically unavoidable as far as I can tell.

**Comment by ghost** [comment]
> Thinking about it briefly, I don't see how this can be mitigated entirely without removing the use of ETags entirely. It could perhaps be partially mitigated by having the client choose a deterministic algorithm for generating the ETag (such as a predetermined hash function) and only accept/save a new ETag if it can be reproduced locally. However, this would require control over the server's ETag generation method, which would limit the environments we can deploy to and increase our infrastructure maintenance burden. But I haven't thought about this much, so there could be flaws in my logic here.

I had not considered that some infrastructure may not permit control over this.
The problem I see is that the ETag is opaque. Solution: you define it on the client as more restricted than opaque. I was thinking that it could just be a timestamp, revision, or hash that the client checks. The idea being that the client does any more than simply byte by byte compare it.

> Unfortunately when it comes to other features, there are many practical ways to track users across network requests. This is largely due to app update checks and app installations themselves, since they reveal to the server which apps the client has installed from Accrescent as well as various device attributes used to obtain the correct split APKs such as the user's preferred language, device architecture, and screen pixel density. Once app listing localization is supported, this will provide another data point by which a specific client (or at least a smaller pool of clients) could be identified. The tracking potential of update checks could be mitigated by spreading out individual update checks for different apps over a significant period of time, but the problem of revealing identifying device attributes to the server is practically unavoidable as far as I can tell.

I had very much considered this prior, so I cede that my request is not feasible or useful. Accrescent by design fingerprints client devices in order to save bandwidth and send appropriate binaries.
